In [1]:
!pip install -q tensorflow_text


In [1]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

2026-02-20 17:31:42.166220: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1771608702.345484      55 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1771608702.397438      55 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1771608702.833319      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771608702.833370      55 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1771608702.833373      55 computation_placer.cc:177] computation placer alr

In [2]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3"
encoder_url = "https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-12_H-768_A-12/2"


In [3]:
preprocess = hub.KerasLayer(preprocess_url)
encoder = hub.KerasLayer(encoder_url, trainable=False)

I0000 00:00:1771608736.229369      55 gpu_device.cc:2019] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 15511 MB memory:  -> device: 0, name: Tesla P100-PCIE-16GB, pci bus id: 0000:00:04.0, compute capability: 6.0


In [16]:
text_input = ["this is a simple test sentence","I love data science"]
tokens = preprocess(text_input)
tokens.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [10]:
tokens.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

# input_type_ids are segment IDs.
It tells BERT which sentence each token belongs to inside a single input example.

0 → Sentence A (segment A)

1 → Sentence B (segment B)

In [17]:
tokens['input_type_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

# input_mask tells BERT which positions are real tokens and which positions are padding.

1 → real token (word, subword, CLS, SEP)

0 → padding (just filler to reach max length)

In [18]:
tokens['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],
      dtype=int32)>

# Also called segment IDs or token type IDs.
It is the sequence of token IDs produced by the BERT tokenizer.

These IDs correspond to:

[CLS] token

WordPiece tokens

[SEP] token

Padding (0)

In [19]:
tokens['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[ 101, 2023, 2003, 1037, 3722, 3231, 6251,  102,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0],
       [ 101, 1045, 2293, 2951, 2671,  102,    0,    0,    0,    0,    0,
           0,

In [20]:
outputs = encoder(tokens)
outputs.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

1. pooled_output
Shape: (batch_size, 768)

The CLS sentence embedding

Used for sentence‑level tasks (classification, sentiment)

2. sequence_output
Shape: (batch_size, seq_len, 768)

The embedding for every token

Used for token‑level tasks (NER, QA)

3. encoder_outputs
A list of all hidden layers inside BERT
(12 layers for BERT‑base)

Used when you want layer‑by‑layer representations

4. default
Same as pooled_output

Added for Keras compatibility

In [ ]:


embedding = outputs["pooled_output"]
print(embedding.shape)
print(embedding)


In [ ]:
outputs

In [4]:
type(outputs)

dict

In [5]:
outputs.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [21]:
outputs['sequence_output']

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[-9.1905129e-01,  7.7194649e-01, -3.8947538e-04, ...,
          4.6148753e-01,  9.1193490e-02,  5.8317289e-02],
        [ 5.9308946e-02,  7.6174313e-01,  3.9456069e-01, ...,
          9.1785982e-02,  8.5669465e-02,  1.9113490e-01],
        [-4.8691911e-01,  3.7266958e-01, -5.1264454e-02, ...,
          2.6424509e-01,  5.7054788e-01, -7.4133974e-01],
        ...,
        [-5.5294573e-01,  8.1668806e-01,  1.8279581e-01, ...,
          3.3658764e-01,  2.8000611e-01, -1.9632377e-01],
        [-6.1008596e-01,  9.8609006e-01,  2.8091159e-01, ...,
          3.1127846e-01,  2.5602558e-01, -2.6893714e-01],
        [-1.6920501e-01,  6.5758938e-01,  2.4100670e-01, ...,
          2.0359553e-02, -8.0368578e-02, -3.4688346e-02]],

       [[ 2.9520616e-03, -1.4803430e-01,  4.2531304e-03, ...,
          3.1826976e-01,  2.5526223e-01, -2.2396317e-01],
        [ 6.0529995e-01,  2.3478742e-01,  4.8131336e-02, ...,
          1.7724377e-01,  2.

In [16]:
outputs['pooled_output']

<tf.Tensor: shape=(1, 768), dtype=float32, numpy=
array([[ 2.71882445e-01,  3.86985317e-02,  7.22397804e-01,
        -1.94196284e-01,  1.10492356e-01, -9.99935687e-01,
        -6.56428859e-02,  9.99628067e-01, -1.22855842e-01,
        -1.38359085e-01,  1.97968096e-01,  2.91659266e-01,
         2.95967638e-01,  5.69644980e-02, -9.98044729e-01,
         2.14560762e-01, -2.46366665e-01, -2.25903809e-01,
         2.55392671e-01, -1.96914196e-01,  7.71999136e-02,
        -7.96365440e-01, -1.83433190e-01,  4.03512031e-01,
        -1.01288117e-01, -9.57961798e-01, -4.18922380e-02,
         3.86619456e-02, -1.75954700e-01, -2.06134021e-01,
         8.72188881e-02, -9.95769948e-02,  4.60587859e-01,
         9.92390573e-01, -1.81161493e-01,  1.32779196e-01,
         1.46220680e-02, -1.56196997e-01,  1.79174975e-01,
        -9.18659717e-02, -2.47772947e-01,  3.20776068e-02,
        -8.10682178e-02, -9.52374756e-01, -9.97978032e-01,
        -3.07169825e-01,  1.46966204e-01, -2.30952222e-02,
      